### ISSUE TITLE
RX not working on PICO

### ISSUE THREAD

**Issue by IgnacioEgea96** [dgatf/Pio-UART-RX-RP2040#1]
Hi,
im getting blank spaces when receiving, using UART0 as TX. Using SDK on Visual Studio Code, Cmake.

**Comment by IgnacioEgea96** [comment]
It appears to be an issue with the state machine id overwriting. Defining sm and pio as global gets the job done

**Comment by dgatf** [comment]
Thank you. Fixed with 5d351ce9885efbedf247fec8b5a48ba1db3a634b
